config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  validates :name, presence: true

    def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
 class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  scope :newMessageJadge, -> (message_id){where('id > ?', message_id)}

  validates :body, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages

  # mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :request_path

  def request_path
    @path = controller_path + '#' + action_name
    def @path.is(*str)
        str.map{|s| self.include?(s)}.include?(true)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def edit
    @users = @group.users.where.not(id: current_user.id)
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user).order("created_at ASC")
    respond_to do |format|
      format.html
      format.json {@messages = @group.messages.newMessageJadge(params[:id])}
    end
  end

   def create
     @message = @group.messages.new(message_params)
     if @message.save
       respond_to do |format|
         format.html { redirect_to group_messages_path(@group) }
         format.json
       end
     else
      @messages = @group.messages.includes(:user)
      render :index
    end
  end

  private
  def set_group
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where("name LIKE(?)", "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
     end
    end

  def edit
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      redirect_to edit_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "groups/shared/form", locals: { group: @group}

app/views/groups/index.html.haml
.content
  = render partial: "shared/side-bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "groups/shared/form", locals: {group: @group}

app/views/groups/shared/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :グループ名, class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat_group_name chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
      %input{class: "chat-group-form__input", id: "user-search-field" , placeholder: "追加したいユーザー名を入力してください", name: "keyword", type: "text"}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat-group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix.js-chat-member{id: "chat-group-user-#{current_user.id}"}
          %input{name: "group[user_ids][]", type: 'hidden', value: current_user.id}
          .chat-group-user__name
            =current_user.name
          %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove
            削除
        - if @path.is('groups#edit')
          - @users.each do |user|
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: 'hidden', value: user.id}
              .chat-group-user__name
                =user.name
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove
                削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_flash.html.haml
.flash-function
  -flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
// メッセージ表示部分の部分テンプレートr
.chates{ "data-message-id": "#{message.id}"}
  %p.chates__user
    = message.user.name
  %p.chates__time
    = l(message.created_at,format: :default)
  %p.chates__message
    = message.body
  %p.chates__image
    = image_tag message.image if message.image_url.present?

app/views/messages/index.html.haml
.contents
  / 左サイドの部分テンプレート呼び出し
  = render partial: "shared/side-bar"
  // チャット機能メイン
  .main-content
    // チャット機能メインのヘッダー
    .main-header
      .group-info
        .group-name
          = @group.name
        .members
          %ul.members
            Member：
            %li.members__list
              - @group.users.each do |user|
                = user.name
      .edit-btn
        = link_to "Edit", edit_group_path(@group), class: "edit-btn-form"
    // メッセージ表示機能
    .chat-space
      = render @messages
    // メッセージ送信機能
    = form_for [@group, @message] do |f|
      .input-space
        .post
          .post-area
            = f.text_field :body, class: "message-area", placeholder: "type a message"
            = f.label :image, class: "icon-style-image" do
              %i.fa.fa-picture-o
              = f.file_field :image, class: "display-none"
            = f.submit "send", class: "send-btn"

app/views/partial-template/_side-bar.html.haml
// 左サイドの部分テンプレート
%html
  %head
  %body
    // 左サイド
    .side-bar
      // 左サイドヘッダー
      .side-header
        .username test太郎
        %ul.icons
          %li.icons__list
            = link_to root_path, class: "icon-style" do
              %i.far.fa-edit
          %li.icons__list
            = link_to root_path, class: "icon-style" do
              %i.fa.fa-cog
      // グループ一覧
      = render partial: "partial-template/side-group-info"

app/views/shared/_side-bar.html.haml
// 左サイドの部分テンプレート
.side-bar
  // 左サイドヘッダー
  .side-header
    .username
      = current_user.name
    %ul.icons
      %li.icons__list
        = link_to new_group_path, class: "icon-style" do
          %i.fa.fa-pencil-square-o
      %li.icons__list
        = link_to edit_user_path(current_user), class: "icon-style" do
          %i.fa.fa-cog
  // グループ一覧
  = render partial: "shared/side-group-info"

app/views/shared/_side-group-info.html.haml
/サイドバー内グループ情報の部分テンプレート
.side-group-info
  - current_user.groups.each do |group|
    %h2.side-group
      = link_to "#{group.name}", group_messages_path(group),class: "font-style"
    %p.side-chat
      = link_to "#{group.show_last_message}", group_messages_path(group), class: "font-style"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'